### ISSUE TITLE
Infra/security considerations 

### ISSUE THREAD

**Issue by dublx** [ogcio/feature-flags-ssr-demo#1]
As part of discovery and documentation of findings, I'd like to ask to register in your analysis the following topics:

- runs well in k8s (eg, has Helm charts or at minimum Docker image exists already and pass vulnerabilities scans in ECR)
- good rbac 
- provides audit capabilities: who changed which flag and when 
- day 2 operations / maintenance plans - who will own it 
- what other inra is needed (databases etc)
From a infra and security perspective that's what I have in mind at the moment;

Other general topics 
- analysed differences in performance / latency - supports caching?
- learning curve for developers, and, for the operations teams
- ease of managing flags across multiple environments and services
- impact on unit testing and e2e testing

**Comment by matteolc** [comment]
Hi @dublx 
Please find updated info in the README and the docs folder
